import pandas as pd
import os
import logging
from typing import List
from qts_core.alpha.features import BaseAlpha

logger = logging.getLogger(__name__)

class FeatureRegistry:
    """
    Manages the computation, caching, and retrieval of alpha features.
    Ensures training and live trading environments consume identical feature pipelines.
    """
    def __init__(self, cache_dir: str = "/tmp/feature_store"):
        self.cache_dir = cache_dir
        os.makedirs(self.cache_dir, exist_ok=True)
        self.registered_alphas: List[BaseAlpha] = []

    def register_alpha(self, alpha_generator: BaseAlpha) -> None:
        """Adds an alpha generator to the pipeline."""
        self.registered_alphas.append(alpha_generator)
        logger.info(f"Registered Alpha: {alpha_generator.name}")

    def generate_features(self, raw_data: pd.DataFrame, dataset_id: str) -> pd.DataFrame:
        """
        Applies all registered alphas to the raw data and caches the result.
        """
        cache_path = os.path.join(self.cache_dir, f"{dataset_id}_features.parquet")
        
        # Return cached version if it exists to save compute time
        if os.path.exists(cache_path):
            logger.info(f"Loading cached features from {cache_path}")
            return pd.read_parquet(cache_path)
            
        logger.info(f"Computing {len(self.registered_alphas)} features for {dataset_id}...")
        feature_df = raw_data.copy()
        
        for alpha in self.registered_alphas:
            feature_df[alpha.name] = alpha.compute(raw_data)
            
        # Drop NaN values generated by rolling windows
        feature_df.dropna(inplace=True)
        
        # Save to feature store
        feature_df.to_parquet(cache_path)
        logger.info(f"Features cached to {cache_path}")
        
        return feature_df